export const FETCH_CONTENT_START = 'FETCH_CONTENT_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_CONTENT_ERROR = 'FETCH_CONTENT_ERROR';
export const FETCH_TVSHOWS_SUCCESS = 'FETCH_TVSHOWS_SUCCESS';
export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_HOMEPAGE_SUCCESS = 'FETCH_HOMEPAGE_SUCCESS';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
